### ISSUE TITLE
jump to date

### ISSUE THREAD

**Issue by stefanmdt** [restorando/angular-pickadate#40]
Hi! Is it possible to jump to a specific date by changing the model value? As far as I can see, this is only possible if the date is in the same month as the current date, right?

I changed the following line and removed the currentDate, then its working. But this destroys some logic I guess.

    scope.currentDate = scope.currentDate || firstSelectedDate || new Date();

Should "isOutOfRange" also compare the year and not only the month?

    date < minDate || date > maxDate || dateFilter(date, 'M') !== dateFilter(scope.currentDate, 'M');

Thx in advance ...

**Comment by gschammah** [comment]
hi @stefanmdt 

In the next release of the library this will be fixed. I assume it will be live some day this week.

Thanks

**Comment by stefanmdt** [comment]
Nice, thanks.

**Comment by gschammah** [comment]
@stefanmdt fixed in version 1.0.0
