### ISSUE TITLE
Date change does not work if the new month is different than the current

### ISSUE THREAD

**Issue by Kraku** [restorando/angular-pickadate#46]
It is not possible to change the date by a model if the new month is different than the current.

example:
```js
$scope.date = '2015-03-12';
```

```html
<button type="button" ng-click="data='2015-04-12'">click</button>
```

After click $scope.date will be undefined.

**Comment by gschammah** [comment]
This is working in the latest version.

http://plnkr.co/edit/nnkKVJgm9lmv9cdTmvvU?p=preview

Can you please double check to see if my demo is reproducing your case?

**Comment by Kraku** [comment]
Last version (e89022cfb5ab7abbb26139b05a62f9147fd8f247) works correctly, thanks!
