### ISSUE TITLE
Multiple attribute works only within single month 

### ISSUE THREAD

**Issue by adyba** [restorando/angular-pickadate#49]
Once trying to get dates from multiple months it has two (inappropriate) behaviors : 
- Once the selection starts ex.in April and then some May date to be added. The calendar jumps back to April; model array is not changed. 
- Once the selection starts in May and user rolls back into April, the model is destroyed/replaced (?) by April input(s).

**Comment by gschammah** [comment]
Hi @adyba 

I couldn't reproduce any of the 2 issues. Could you please create a plunker to reproduce it?

you can fork this one: http://plnkr.co/edit/nnkKVJgm9lmv9cdTmvvU?p=preview

**Comment by adyba** [comment]
Well the plunk provided works fine, I have spend on this a long night so I have probably brought some homemade bug into the code. Mea culpa.
