### ISSUE TITLE
How to disable weekends?

### ISSUE THREAD

**Issue by vnn456** [restorando/angular-pickadate#74]
<div select-other-months="next" pickadate="" ng-model="date" min-date="minDate" disabled-dates="holidays"></div>
 $scope.holidays= [1, 7, '2016-04-07'];

**Comment by diegohaz** [comment]
I've created a pull request #76 for this

**Comment by gschammah** [comment]
Hi there,

I created a PR adding a more flexible way to declare disabled dates. Please check #77 (note: it's a breaking change)

Thanks
