### ISSUE TITLE
expensiveCheckFn

### ISSUE THREAD

**Issue by thegitfather** [restorando/angular-pickadate#78]
Not sure whats going exactly wrong here but this is my scenario (using Angular 1.5.3):
1. uploading some images with a form where I also use pickadate
2. after all uploads finished I change the state to the new gallery (using `ui.router`)
3. opening an thumb-image with ngDialog
4. some event to show next image

First I thought the problem is on my side but I figured out that the problem doesn't occur when I
a) do a hard reload after the state change or
b) remove pickadate from my app

Is there some way to destroy pickadate after the state change? or how to check if my state is clean - the new state has no pickadate directives in it..

```
angular.js:13424 Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.5.3/$rootScope/inprog?p0=%24apply
    at angular.js:68
    at beginPhase (angular.js:17383)
    at Scope.$apply (angular.js:17123)
    at togglePicker (angular-pickadate.js:70)
    at HTMLDocument.<anonymous> (angular-pickadate.js:84)
    at defaultHandlerWrapper (angular.js:3417)
    at HTMLDocument.eventHandler (angular.js:3405)
    at Scope.scope.openNext (galleryItem.directive.js:32)
    at fn (eval at <anonymous> (angular.js:14268), <anonymous>:4:215)
    at expensiveCheckFn (angular.js:15281)
```

`angular-pickadate.js:70` indeed has an apply call: `scope.$apply();`. Any idea whats causing the error?

**Comment by gschammah** [comment]
What version of angular-pickadate are you using?

**Comment by thegitfather** [comment]
I've tried v1.1.0 and v2.0.0. Both same result

**Comment by thegitfather** [comment]
After some refactoring the message is gone :astonished:. Since nothing was broken anyways I guess this issue is not important or my setup was just a bit unusual...
